# Generated by Django 4.1.4 on 2022-12-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='headline',
            new_name='todo',
        ),
    ]
