# Generated by Django 4.1.4 on 2022-12-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_upload_delete_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='venu_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
