# Generated by Django 4.1.5 on 2023-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0006_resume_skillset'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='fd',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
