# Generated by Django 4.1.5 on 2023-01-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_resume_fd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='fd',
        ),
    ]
